blog/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<int:pk>/", views.blog_detail, name="blog_detail"),
    path("<int:pk>/delete/", views.blog_delete, name="blog_delete"),
    path("author/<str:author>",views.blog_author, name="blog_author"),
    path("accounts/", include("django.contrib.auth.urls")),
    path('register/',views.register,name="register"),
    path("<str:category>/", views.blog_category, name="blog_category"),
] 

portfolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Adding a path to my projects.urls
    path('', RedirectView.as_view(url="/projects")),
    path('projects/', include('projects.urls')),
    path('blog/', include("blog.urls"))
]

projects/urls.py
from django.contrib import admin
from django.urls import include, path
from projects import views

app_name = "projects"

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>',views.project_detail, name="project_detail"),
    # path("blog/", include("blog.urls")),
]

blog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=20,unique=True)
  
  def __str__(self):
    return f'{self.name}'

class Post(models.Model):
  title = models.CharField(max_length=255)
  body = models.TextField()
  author = models.TextField()
  created_on = models.DateTimeField(auto_now_add=True)
  last_modified = models.DateTimeField(auto_now=True)
  categories = models.ManyToManyField('Category',related_name='posts')
  
  def __str__(self):
    return f'{self.title}'

class Comment(models.Model):
  author = models.CharField(max_length=60)
  body = models.TextField()
  created_on = models.DateTimeField(auto_now_add=True)
  post = models.ForeignKey('Post', on_delete=models.CASCADE)

projects/models.py
from django.db import models
from datetime import date

# Create your models here.
class Project(models.Model):
  title = models.CharField(max_length=100)
  description = models.TextField()
  technology = models.CharField(max_length=20)
  image = models.CharField(max_length=100)
  date_created = models.DateField(default=date.today)
  

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )
    
class PostForm(forms.Form):
    # author = forms.CharField(
    #     max_length=60,
    #     widget=forms.TextInput(attrs={
    #         "class": "form-control",
    #         "placeholder": "Your Name"
    #     })
    # )
    title = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Title"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Blog body"
        })
    )
    categories = forms.CharField(widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "placeholder": "Categories"   
        }
    ))
    
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

blog/views.py
from blog.forms import CommentForm, CustomUserCreationForm, PostForm
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.urls import reverse
from blog.models import Category, Post, Comment

# Create your views here.
def blog_index(request):
  form = PostForm()
  if request.method == 'POST':
    form = PostForm(request.POST)
    if form.is_valid():
      categories_input = form.cleaned_data["categories"].split(";")
      post = Post.objects.create(
        body = form.cleaned_data['body'],
        title = form.cleaned_data['title'],
        author = str(request.user),
      )
      for category in categories_input:
        cat, _ = Category.objects.get_or_create(name=category)
        post.categories.add(cat)
      post.save()
  posts = Post.objects.all().order_by('-created_on')
  context = {
    "posts": posts,
    "title": "All Blogs",
    "form": form
  }
  return render(request,"blog_index.html", context)

def blog_category(request, category):
  posts = Post.objects.filter(
    categories__name__contains = category
  ).order_by(
    '-created_on'
  )
  
  context = {
    "category": category,
    "posts": posts,
    "isAuthor": False,
    "title": f'{category} Posts'
  }
  
  return render(request,"blog_category.html", context)

def blog_author(request, author):
  posts = Post.objects.filter(
    author__contains = author
  ).order_by(
    '-created_on'
  )
  
  context = {
    "category": author,
    "isAuthor": True,
    "posts": posts,
    "title": f'{author} Posts'
  }
  
  return render(request,"blog_category.html", context)

def blog_delete(request,pk):
  Post.objects.get(pk=pk).delete()
  return blog_index(request)

def blog_detail(request, pk):
  post = Post.objects.get(pk=pk)
  
  form = CommentForm()
  if request.method == 'POST':
    form = CommentForm(request.POST)
    if form.is_valid():
      comment = Comment(
        author = form.cleaned_data['author'],
        body = form.cleaned_data['body'],
        post = post
      )
      comment.save()
  
  comments = Comment.objects.filter(post=post)
  context = {
    "comments": comments,
    "post": post,
    "form": form,
    "title": f'{post.title}'
  }
  
  return render(request,"blog_detail.html", context)

def register(request):
    if request.method == "GET":
        return render(
            request, "register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.backend = "django.contrib.auth.backends.ModelBackend"
            user.save()
            login(request, user)
            return redirect("blog_index")
        else:
            return render(
            request, "register.html",
            {"form": CustomUserCreationForm, "message": True}
        )

projects/views.py
from projects.models import Project
from django.http.response import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse 

# Create your views here.
def project_list(request):
  return render(request,'projects/index.html')

def all_projects(request):
  #query the database to return all project objects
  projects = Project.objects.all()
  return render(request,'projects/all_projects.html',{'projects':projects})

def project_detail(request, pk):
  project = Project.objects.get(pk=pk)
  return render(request,'projects/detail.html', {'project':project})

blog/templates/blog/blog_category.html
{% extends "projects/base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    {% if isAuthor %}
        <h1>Posts by {{ category | title }}</h1>
    {% else %}
        <h1>{{ category | title }}</h1>
    {% endif %}
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'blog_detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            <a href="{% url 'blog_author' post.author %}">{{post.author}}</a> |&nbsp;
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "projects/base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <p class="text-muted">{{comment.created_on}}</p>
    <hr>
    {% endfor %}
    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/blog_index.html
{% extends "projects/base.html" %}

{% block content %}
<div class="col-md-8 offset-md-2">
  <div>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'password_change' %}">Change password</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
  </div>
  <h1>Blog Index</h1>
  <hr>
  <form action="/blog/" method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.title }}
    </div>
    <div class="form-group">
        {{ form.body }}
    </div>
    <div class="form-group">
        {{ form.categories }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
  {% for post in posts %}
    <h2><a href="{% url 'blog_detail' post.pk%}">{{ post.title }}</a></h2>
    <small>
        <a href="{% url 'blog_author' post.author %}">{{post.author}}</a> |&nbsp;
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    <a href="{% url 'blog_delete' post.pk %}">Delete</a>
  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'projects/base.html' %}

{% block content %}
<h2>Register</h2>

{% if message %}
        <p>Invalid</p>
{% endif %}


<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register">
</form>

<a href="{% url 'login' %}">Back to login</a>
{% endblock %}

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
  <div class="container">
    <h1>Projects</h1>
    <div class="row">
      {% for project in projects %}
          <div class="col-md-4">
              <div class="card bg-light mb-3">
                  <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}">
                  <div class="card-body">
                      <h5 class="card-title">{{ project.title }}</h5>
                      <p class="card-text">{{ project.description }}</p>
                      <p class="card-subtitle mb-2 text-muted">{{project.date_created}}</p>
                      <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">Read More</a>
                  </div>
              </div>
          </div>
      {% endfor %}
      </div>
  </div>
{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'projects:all_projects' %}">David Nagarpowers</a>
      <button class="navbar-toggler" type="button" data-target=".navbar-collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'projects:all_projects' %}">Home </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">About Me </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog_index' %}">Blog </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Contact </a>
          </li>
        </ul>
        <form action="#" class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </div>
  
  <div class="container">
    {% block content%}

    {% endblock %}
  </div>
 
</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
  <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="{{ project.description }}" width="60%">
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{ project.description }}</p>
            <h5>Built with:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
{% endblock %}